apiVersion: v1
kind: Service
metadata:
  name: hello-docker-service
spec:
  type: NodePort
  selector:
    app: hello-docker
  ports:
    - protocol: TCP
      port: 8080 # Porta do serviço
      targetPort: 8080 # Porta do container
      nodePort: 30007